"""Add delay and distance to TrafficLog

Revision ID: 7ae8eee13828
Revises: 20d761abb933
Create Date: 2026-03-03 13:57:45.617377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae8eee13828'
down_revision: Union[str, Sequence[str], None] = '20d761abb933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trafficlog', sa.Column('delay_seconds', sa.Integer(), nullable=False))
    op.add_column('trafficlog', sa.Column('distance_meters', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trafficlog', 'distance_meters')
    op.drop_column('trafficlog', 'delay_seconds')
    # ### end Alembic commands ###
