"""baseline schema

Revision ID: 20d761abb933
Revises:
Create Date: 2026-03-02 19:01:24.143865

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20d761abb933"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trafficlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("checked_at", sa.DateTime(), nullable=False),
        sa.Column("duration_in_traffic", sa.Integer(), nullable=False),
        sa.Column("normal_traffic_duration", sa.Integer(), nullable=False),
        sa.Column("traffic_status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trafficlog")
    # ### end Alembic commands ###
