"""add phone number to user

Revision ID: fc8e73d37f8b
Revises: 0ea358d22418
Create Date: 2026-03-13 19:23:15.915178

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc8e73d37f8b"
down_revision: Union[str, Sequence[str], None] = "0ea358d22418"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "phone_number", sa.String(), nullable=False, server_default="0000000000"
        ),
    )
    op.create_index(
        op.f("ix_user_phone_number"), "user", ["phone_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_phone_number"), table_name="user")
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###
